# ホーム＆ビジターの投球内容について

## プロ野球のホーム＆ビジターの投球内容をK/9とBB/9の両面から分析を行う

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')

try:
    xrange
except NameError:
    xrange = range

from __future__ import print_function

### 1. データの読み込み

In [3]:
dataset = pd.read_csv("csv/enjoy_baseball/result.csv")

In [4]:
dataset.head()

   HOME_K VISITOR_IP       Team  VISITOR_K  Year  HOME_BB  VISITOR_BB HOME_IP
0     508        625     Giants        484  2015      180         195     646
1     505    620+1/3  Buffaloes        450  2015      215         261     643
2     506    624+2/3     Eagles        517  2015      208         248     663
3     527    630+1/3       Carp        483  2015      217         202     656
4     581    608+1/3     Tigers        509  2015      214         238     664

In [5]:
def ip_to_real(x):
    #最初の４文字を取り出せば、年になる
    return float(eval(x))

dataset["HOME_K/9"] = dataset["HOME_K"] * 9 / dataset["HOME_IP"].apply(ip_to_real)
dataset["HOME_BB/9"] = dataset["HOME_BB"] * 9 / dataset["HOME_IP"].apply(ip_to_real)
dataset["HOME_K/BB"] = dataset["HOME_K"] / dataset["HOME_BB"]
dataset["VISITOR_K/9"] = dataset["VISITOR_K"] * 9 / dataset["VISITOR_IP"].apply(ip_to_real)
dataset["VISITOR_BB/9"] = dataset["VISITOR_BB"] * 9 / dataset["VISITOR_IP"].apply(ip_to_real)
dataset["VISITOR_K/BB"] = dataset["VISITOR_K"] / dataset["VISITOR_BB"]
dataset["HOME_K/BB / VISITOR_K/BB"] = dataset["HOME_K/BB"] / dataset["VISITOR_K/BB"]

In [6]:
dataset[dataset["HOME_K/BB / VISITOR_K/BB"] < 1].sort_values(by=["Team", "Year"], ascending=True)

,HOME_K,VISITOR_IP,Team,VISITOR_K,Year,HOME_BB,VISITOR_BB,HOME_IP,HOME_K/9,HOME_BB/9,HOME_K/BB,VISITOR_K/9,VISITOR_BB/9,VISITOR_K/BB,HOME_K/BB / VISITOR_K/BB
48,479,624+1/3,Baystars,452,2013,299,252,655,6.581679,4.108397,1.602007,6.515750,3.632675,1.793651,0.893154
58,470,620+2/3,Carp,463,2014,226,182,663,6.380090,3.067873,2.079646,6.713749,2.639098,2.543956,0.817485
9,500,610,Dragons,466,2015,230,195,669,6.726457,3.094170,2.173913,6.875410,2.877049,2.389744,0.909685
19,460,621+2/3,Fighters,458,2011,155,153,652,6.349693,2.139571,2.967742,6.630563,2.215013,2.993464,0.991407
31,418,624+2/3,Fighters,450,2012,193,189,655,5.743511,2.651908,2.165803,6.483458,2.723052,2.380952,0.909637
39,385,620+1/3,Fighters,439,2013,249,251,656,5.282012,3.416159,1.546185,6.369156,3.641591,1.749004,0.884037
6,501,622+2/3,Fighters,492,2015,253,218,654,6.894495,3.481651,1.980237,7.111349,3.150964,2.256881,0.877422
37,519,631+2/3,Giants,502,2012,184,174,654,7.142202,2.532110,2.820652,7.152507,2.479156,2.885057,0.977676
20,458,627+1/3,Lions,402,2011,173,150,654,6.302752,2.380734,2.647399,5.767269,2.151966,2.680000,0.987835
42,481,630+2/3,Lions,503,2013,211,208,660,6.559091,2.877273,2.279621,7.178118,2.968288,2.418269,0.942666
52,481,618+1/3,Lions,433,2014,273,242,670,6.461194,3.667164,1.761905,6.302426,3.522372,1.789256,0.984714
33,366,619+2/3,Marines,396,2012,169,167,653,5.044410,2.329250,2.165680,5.751479,2.425498,2.371257,0.913305
5,455,621+2/3,Marines,471,2015,212,216,643,6.368585,2.967341,2.146226,6.818767,3.127078,2.180556,0.984257
11,488,612+2/3,Swallows,447,2015,235,194,660,6.654545,3.204545,2.076596,6.566376,2.849837,2.304124,0.901252

In [7]:
dataset[dataset["Team"] == 'Fighters'][["Year" ,"Team", "HOME_K/BB", "VISITOR_K/BB", "HOME_K/BB / VISITOR_K/BB"]]

    Year      Team  HOME_K/BB  VISITOR_K/BB  HOME_K/BB / VISITOR_K/BB
6   2015  Fighters   1.980237      2.256881                  0.877422
19  2011  Fighters   2.967742      2.993464                  0.991407
31  2012  Fighters   2.165803      2.380952                  0.909637
39  2013  Fighters   1.546185      1.749004                  0.884037
51  2014  Fighters   2.040323      1.968127                  1.036682

In [8]:
dataset[dataset["HOME_K/BB / VISITOR_K/BB"] > 1.2].sort_values(by=["Team", "Year"], ascending=True)

,HOME_K,VISITOR_IP,Team,VISITOR_K,Year,HOME_BB,VISITOR_BB,HOME_IP,HOME_K/9,HOME_BB/9,HOME_K/BB,VISITOR_K/9,VISITOR_BB/9,VISITOR_K/BB,HOME_K/BB / VISITOR_K/BB
17,510,619,Buffaloes,508,2011,157,203,658,6.975684,2.147416,3.248408,7.386107,2.951535,2.502463,1.298084
1,505,620+1/3,Buffaloes,450,2015,215,261,643,7.068429,3.009331,2.348837,6.528748,3.786674,1.724138,1.362326
28,508,619+1/3,Carp,447,2012,195,224,653,7.001531,2.687596,2.605128,6.495694,3.255113,1.995536,1.305478
36,492,622+1/3,Dragons,385,2012,157,167,663,6.678733,2.131222,3.133758,5.567756,2.415104,2.305389,1.359318
49,534,640+1/3,Giants,464,2014,186,194,666,7.216216,2.513514,2.870968,6.521603,2.726705,2.391753,1.200362
16,571,630+2/3,Hawks,496,2011,137,168,656,7.833841,1.879573,4.167883,7.078224,2.397463,2.952381,1.411702
30,531,623+1/3,Hawks,452,2012,203,220,652,7.329755,2.802147,2.615764,6.526203,3.176471,2.054545,1.273159
44,554,622+1/3,Hawks,431,2013,226,266,664,7.509036,3.063253,2.451327,6.232994,3.846813,1.620301,1.512884
8,626,627+1/3,Hawks,503,2015,204,223,672,8.383929,2.732143,3.068627,7.216259,3.199256,2.255605,1.360445
12,476,610+2/3,Marines,398,2014,216,228,666+1/3,6.429215,2.917459,2.203704,5.865721,3.360262,1.745614,1.262423
47,512,623+1/3,Swallows,453,2013,229,252,662,6.960725,3.113293,2.235808,6.540642,3.638503,1.797619,1.243761
22,597,622+1/3,Tigers,522,2011,178,201,644,8.343168,2.487578,3.353933,7.549009,2.906802,2.597015,1.291457
14,564,617+1/3,Tigers,421,2012,185,199,655,7.749618,2.541985,3.048649,6.137689,2.901188,2.115578,1.441048
4,581,608+1/3,Tigers,509,2015,214,238,664,7.875000,2.900602,2.714953,7.530411,3.521096,2.138655,1.269467

In [15]:
dataset[["Year", "Team", "HOME_K/BB"]].sort_values(by=["HOME_K/BB"], ascending=False)

    Year       Team  HOME_K/BB
16  2011      Hawks   4.167883
22  2011     Tigers   3.353933
17  2011  Buffaloes   3.248408
23  2011    Dragons   3.209459
15  2011     Eagles   3.182390
36  2012    Dragons   3.133758
8   2015      Hawks   3.068627
14  2012     Tigers   3.048649
19  2011   Fighters   2.967742
55  2014  Buffaloes   2.910891
26  2011     Giants   2.872222
49  2014     Giants   2.870968
46  2013     Giants   2.839806
0   2015     Giants   2.822222
37  2012     Giants   2.820652
27  2012     Eagles   2.816568
59  2014     Tigers   2.761682
25  2011   Swallows   2.730159
18  2011    Marines   2.723270
4   2015     Tigers   2.714953
21  2011       Carp   2.698980
45  2013     Tigers   2.678571
20  2011      Lions   2.647399
30  2012      Hawks   2.615764
28  2012       Carp   2.605128
13  2013  Buffaloes   2.540284
29  2012  Buffaloes   2.488764
44  2013      Hawks   2.451327
24  2011   Baystars   2.450000
2   2015     Eagles   2.432692
3   2015       Carp   2.428571
53  2014      Hawks   2.405063
54  2014     Eagles   2.372197
1   2015  Buffaloes   2.348837
42  2013      Lions   2.279621
10  2015   Baystars   2.275109
41  2013     Eagles   2.253521
47  2013   Swallows   2.235808
12  2014    Marines   2.203704
50  2014   Baystars   2.198157
9   2015    Dragons   2.173913
31  2012   Fighters   2.165803
33  2012    Marines   2.165680
5   2015    Marines   2.146226
32  2012      Lions   2.105000
58  2014       Carp   2.079646
11  2015   Swallows   2.076596
51  2014   Fighters   2.040323
43  2013    Marines   2.038961
38  2013       Carp   2.034632
6   2015   Fighters   1.980237
57  2014   Swallows   1.968504
40  2013    Dragons   1.959677
35  2012   Swallows   1.951754
56  2014    Dragons   1.941634
7   2015      Lions   1.889362
34  2012   Baystars   1.806452
52  2014      Lions   1.761905
48  2013   Baystars   1.602007
39  2013   Fighters   1.546185